controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# A way to handle routes (not used much)
# home:
#     path: /
#     controller: App\Controller\HomeController::index
